# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.author }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sorceress
description: Sorcery is a practice of casting spells, communicate with and embody demons and other spirits to affect the natural order of things or to provide a desirable outcome in certain situations. A sorceress is a female that practices sorcery.
baseurl: "/sorceress"
url: "https://chethanbhat.github.io/sorceress/"
exclude:
  - README.md
  - LICENSE.txt

# Social media
twitter_username:
twitter_image:
facebook_app_id:
facebook_image:
google_analytics:

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

# Outputting
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

# Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

# jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layout: category_archives
  permalinks:
    category: /categories/:name/
